### ISSUE TITLE
works initially, then get "preview not available"

### ISSUE THREAD

**Issue by teripratt** [petkivim/embed-google-docs#1]
Embeded a google sheet.  viewed fine at first now am getting "preview not available".

**Comment by petkivim** [comment]
Hi,

Have you checked the sharing settings of the document? The settings should be set to "Anyone with the link" or "Public on the web.

https://support.google.com/drive/answer/2494886?hl=en

Best regards,
Petteri

**Comment by jk15060** [comment]
I'm getting the same error (preview not available) trying to get Google Docs Viewer Plugin to work on my Joomla 3.4.8 website.  I'm not quite sure what I should be using for the Base URL since I'm using Google Drive.  I did find this link http://googlesystem.blogspot.com/2015/02/google-docs-viewer-page-no-longer.html that talked about changing the base url to 
https://docs.google.com/viewer?url=  (this is what I am using for my base URL)

I have three questions.  First, is that a correct base URL for display PDFs I have in folders on Google Drive?  I have two public folders under "My Drive" that are visible to the Public, as are all the PDFs within those two folders.
Second, can I reference the entire folder of PDFs?
Third, if I cannot reference the entire public folder, how do I determine the URL of each PDF?
Ok, so I have another question.  I still use {google_docs}URL to PDF{/google_docs} within the Joomla article, right?

Thank you in advance for any help that might be out there today.

**Comment by petkivim** [comment]
Unfortunately the plugin doesn't support embedding entire folders, only single files are currently supported. However, you can embed multiple files on a single page. Embedding a PDF file can be done like this.

1. Go to your Google Drive account
2. Right click the file you want to embed
3. Select Share
4. Change to "Anyone with the link can view"
5. Copy the link
```
https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/view?usp=sharing
```
6. Modify the last part of the link: 
```
https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/preview
```
7. Embed the below code on a Joomla article
```
{google_docs}https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/preview{/google_docs}
```
8. Repeat these steps for each file you want to embed.

**Comment by jk15060** [comment]
I can’t thank you enough for the speedy reply!  I was closer to getting this right than I thought.  I actually reverted back to an External Link (for my Joomla menu) and am able to open the FOLDER of all PDFs in that folder.  

 

I did want to know how to embed one if at all possible and you have shown me the error of my configuration.

 

MANY THANKS!  

 

Janis

**Comment by petkivim** [comment]
You're welcome! I'm glad to hear that the problem was solved. :)

Petteri

**Comment by jk15060** [comment]
I get an error 400.  Do you think that’s due to my base URL which is this:  https://docs.google.com/viewer?url=

 

Or should I leave that blank in the plugin?

 

Guess I spoke too soon.  I was just very happy to get a same-day reply.

 

Thanks again

**Comment by jk15060** [comment]
DISREGARD last email message.  Works like a charm!!!

 

http://www.joomlawebdesignnc.com/newsletters.html

 

Many many thanks Petteri!!

**Comment by petkivim** [comment]
You're welcome. The site looks good. :)

Petteri

**Comment by zainraj** [comment]
hye everyone... i am getting the same error while vewing the doc file on a browser.. i am using the google docs viewer for that but it shows the error that no preview available kindly help me out here is my code.........
         echo '<iframe src="https://docs.google.com/gview?url=mydoc.doc&embedded=true" style="width: 100%;"></iframe>';

**Comment by petkivim** [comment]
Hi @zainraj 

Have you defined base URL in the plugin's settings?

https://github.com/petkivim/embed-google-docs#base-url

If you haven't defined the base URL, then you must use the full URL when embedding a document. When the base URL is not defined, the plugin considers Joomla's install directory's URL as the base URL.vBased on the code below you have used only the document name: `mydoc.doc`.

```
<iframe src="https://docs.google.com/gview?url=mydoc.doc&embedded=true" style="width: 100%;"></iframe>
```

Best regards,
Petteri

**Comment by zainraj** [comment]
echo '<iframe
src="https://docs.google.com/gview?url=http://192.168.0.56/orangehrm/admin/images/'.$file.'&embedded=true"
style="width: 100%;"></iframe>';
i have used the complete url inside get variable of url in the iframe
but it shows me error message that no preview available..

**Comment by petkivim** [comment]
The correct syntax to embed a document is this:

```
{google_docs}http://www.example.com/docs/document.pdf{/google_docs}
```

The use of PHP code and/or variables in the document URL is not supported so you should replace `$file` with the name of the file that you want to embed. In addition, you cannot use a private IP ( `192.168.0.56`) in the document URL, you must replace it with a public IP or publicly resolvable DNS name.

Regards,
Petteri
