### ISSUE TITLE
PDFs are not displayed

### ISSUE THREAD

**Issue by maxstorch** [petkivim/embed-google-docs#10]
Very good plugin! Has been working pretty well for year!

Suddendly, we got a problem... Any ideas why it may not work?
https://storchevoy.ru/index.php/10-for-academics/literature/papers/6-storchevoj-m-a-normativnaya-etika-biznesa-problemy-primeneniya

**Comment by petkivim** [comment]
Hi,

Thank you for your message. I noticed that you're not using HTTPS when you're embedding the document. Try to set the plugin's HTTPS setting to Yes in the admin backend. It has helped other users with similar issues before.

**Comment by maxstorch** [comment]
Dear Petteri, thanks, it works!

**Comment by petkivim** [comment]
You're welcome. :)
