### ISSUE TITLE
Error message after upgrading til PHP 7

### ISSUE THREAD

**Issue by jankorshavn** [petkivim/embed-google-docs#11]
Hi,
After upgradring to PHP 7, I get the following error messages from your Google Doc embedder.

plgContentembed_google_docs_viewer has a deprecated constructor in /home/ostfopip/public_html/plugins/content/embed_google_docs_viewer/embed_google_docs_viewer.php on line 18

Will you be upgrading this extension anytime soon?

Best rgds,
Jan Korshavn

**Comment by thepiston** [comment]
yes, same issue for me, hopefully an updated version compatible with PHP7 is coming?

**Comment by petkivim** [comment]
Yes, I will update the extension within the next few days so the fix is on the way.

- Petteri

**Comment by thepiston** [comment]
thanks! please reply to this thread if you can when done

**Comment by petkivim** [comment]
The version 1.4.4 is now available and it includes support for PHP 7. You can download it at:

https://github.com/petkivim/embed-google-docs/releases/tag/v.1.4.4

Thanks,
Petteri

**Comment by thepiston** [comment]
thank you!
