### ISSUE TITLE
Make the header disappear

### ISSUE THREAD

**Issue by darkmall74** [petkivim/embed-google-docs#13]
Dear Petteri. When Viewer displays the Google document, it adds a grey header with the name of the actual document on the top. Is there a way to make it disappear so that it does not display the grey bar with the name of the document? Or is this a joomla-related setting maybe? I set up the site not to display any additional information except for the actual content which in my case is always a Google Document embedded into Google Viewer.
![screenshot](https://cloud.githubusercontent.com/assets/28643121/25985736/7c0c107e-36ec-11e7-937c-dbb03b7ec0ce.jpg)

**Comment by petkivim** [comment]
Unfortunately the header is a feature of Google Docs and it's not possible to hide it when embedding a Google Document. However, when embedding a PDF file  using Google Docs Viewer the header is not shown.

Thanks,
Petteri
