### ISSUE TITLE
The plugin does not show the pdf-file

### ISSUE THREAD

**Issue by histfan** [petkivim/embed-google-docs#14]
Hello Petteri

The plugin does not show the pdf-file. I used the command {google_docs}http://furesoeseniorklub.dk/images/historie/2017/naverhulen.pdf{/google_docs} and the result was the message (in danish) Der er intet eksempel (there is no example).
I can't see what I am doing wrong and I hope you  can help me.
Thank you very much and kind regards
Dieter

**Comment by histfan** [comment]
Hello again

I tried also with another pdffile. See the page here: https://vaerloesehistorie.dk/embedgoogle.html
I hope, that you can help me. 
Kind regards 
Dieter

**Comment by petkivim** [comment]
Hi Dieter,

Thank you for your message. It's nice to hear that you're using my plugin.

I checked your site and I noticed that the URL of the file that you're trying to embed contains some HTML formatting which is why the viewer is not able to show the file.

```
https://docs.google.com/viewer?url=https%3A%2F%2Fvaerloesehistorie.dk%2F%3Ca+href%3D%22images%2Farkiv%2Fpdf%2Ftest.pdf%22%3Ehttps%3A%2F%2Fvaerloesehistorie.dk%2Fimages%2Farkiv%2Fpdf%2Ftest.pdf%3C%2Fa%3E%3C%2Fspan%3E%3Cspan+style%3D%22font-size%3A+12.16px%3B%22%3E&amp;embedded=true
```

Please try with the URL below.

```
https://docs.google.com/viewer?url=https%3A%2F%2Fvaerloesehistorie.dk%2Fimages%2Farkiv%2Fpdf%2Ftest.pdf
```

If you copy an URL from a website you must copy/paste the code to notepad first to get rid of all the HTML formatting information, and then copy the code from notepad to Joomla article. After that the code should work as expected.

Regards,
Petteri

**Comment by histfan** [comment]
Hi Petteri,

Many thanks for your help. The plugin works perfectly and I was pretty foolish not to look at the code instead of the editor window.
Once again thanks and best regards

Dieter

Fra: Petteri Kivimäki [mailto:notifications@github.com]
Sendt: 11. oktober 2017 17:21
Til: petkivim/embed-google-docs <embed-google-docs@noreply.github.com>
Cc: histfan <dieterbolt@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [petkivim/embed-google-docs] The plugin does not show the pdf-file (#14)


Hi Dieter,

Thank you for your message. It's nice to hear that you're using my plugin.

I checked your site and I noticed that the URL of the file that you're trying to embed contains some HTML formatting which is why the viewer is not able to show the file.

https://docs.google.com/viewer?url=https%3A%2F%2Fvaerloesehistorie.dk%2F%3Ca+href%3D%22images%2Farkiv%2Fpdf%2Ftest.pdf%22%3Ehttps%3A%2F%2Fvaerloesehistorie.dk%2Fimages%2Farkiv%2Fpdf%2Ftest.pdf%3C%2Fa%3E%3C%2Fspan%3E%3Cspan+style%3D%22font-size%3A+12.16px%3B%22%3E&amp;embedded=true

Please try with the URL below.

https://docs.google.com/viewer?url=https%3A%2F%2Fvaerloesehistorie.dk%2Fimages%2Farkiv%2Fpdf%2Ftest.pdf

If you copy an URL from a website you must copy/paste the code to notepad first to get rid of all the HTML formatting information, and then copy the code from notepad to Joomla article. After that the code should work as expected.

Regards,
Petteri
