### ISSUE TITLE
Unable to Load File

### ISSUE THREAD

**Issue by Jacp101** [petkivim/embed-google-docs#16]
Hello, 

I recently started experimenting with a demo joomla account and I stumbled upon this plugin of yours. 

I published one of my shared google spreasheets for testing but I recieve the followin error message on my page: Unable to Load File. 

URL where the unable messages comes up: http://jacpier.demojoomla.com/index.php/kurs
URL that I am trying to share on the webpage:
https://docs.google.com/spreadsheets/d/e/2PACX-1vRlh2hPqL4VO3JBSlS17wtUN2i08am1sdP1y7UvlHFcOzDHOvomVAY_M84twHeUEcD_RXiSbkk9tbms/pubhtml?gid=0&single=true

How I defined it in the article:

![image](https://user-images.githubusercontent.com/22532765/35529922-cd3b82ee-0532-11e8-8ec6-089708851702.png)

I would appreaciate if you could help me with this issue. Note I am fairly new with setting up webpages.

**Comment by Jacp101** [comment]
Seems like I found a solution by googling some more.

All I had to do was to access the manage plugins in Joomla. Locate the Editor - TinyMCE and go to advanced settings and remove iframe from the below section:

![image](https://user-images.githubusercontent.com/22532765/35530934-cfd7517e-0535-11e8-97dc-f0b5e23c49f1.png)

**Comment by petkivim** [comment]
Hi,

That's the correct solution. The plugin uses iframes for embedding the documents so they can not be prohibited.

Regards,
Petteri
