### ISSUE TITLE
View on smartphones

### ISSUE THREAD

**Issue by Jacp101** [petkivim/embed-google-docs#17]
I am having issues with the view that I get on my smartphone, when I view google docs such as google forms and google spreadsheets. 

I have sized them so that they look good on the webpage on a computer, but I don't know how to get them to resize when viewed on a smartphone. 

Any suggestions on how to make sheets and forms be autosized smaller for view on smartphones?

**Comment by petkivim** [comment]
How have you defined the width of the sheets? You should use percentages instead of pixels for defining the width - in that way the sheets and forms are autosized based on the view size of the user. For example:

```
{google_docs}document_url|width:60%{/google_docs}
```

Regards,
Petteri

**Comment by Jacp101** [comment]
Very good. The % way of dooing it seemed to solve the problem. Appreciate the help ty!
