### ISSUE TITLE
Documents are not always loaded

### ISSUE THREAD

**Issue by Deftrax** [petkivim/embed-google-docs#18]
My code is: `{google_docs}otvod_pr.xlsx|width:100%|height:600|border:1|border_style:solid|border_color:#999999{/google_docs}`
Sometimes the page is loading with just blank container instead of displaying document in there.
Here's page for example: [http://ventkharkov.com/index.php/price/9-prices/12-otvody-kruglye](url)
The issue can be reproduced just by reloading several imes.
I also have a screenshot from my provider with 401 error: ![screenshot from 2018-04-23 20_59_06](https://user-images.githubusercontent.com/36643762/39145951-08a4359a-473e-11e8-933d-feda73d41718.png)
Please help. I just dont understand what can I do with this issue.

**Comment by petkivim** [comment]
Thank you for message. You could try to enable `https` when you embed the document. You just have to add `https:yes` parameter to the code.

`
{google_docs}otvod_pr.xlsx|width:100%|height:600|border:1|border_style:solid|border_color:#999999|https:yes{/google_docs}
`

Please let me know if this helped.

**Comment by Deftrax** [comment]
Thank's for advice. I dont know what's going on, but right now the docs are loading every time. I tried reloading page several times on different pages and it's works fine. I didn't do anything with my site.

**Comment by petkivim** [comment]
Probably there was a problem on Google's side and now they have fixed it. This is not the first time when a user reports about a similar problem and the problem goes away by itself within few days.
