### ISSUE TITLE
PDF  de google drive

### ISSUE THREAD

**Issue by MARPENTA** [petkivim/embed-google-docs#2]
Cordial saludo
No he podido incrustar los documentos pdf guardados en google drive. Podrías explicarme como se hace, sigo los pasos que da el documento pero no funciona. Gracias

**Comment by petkivim** [comment]
Hi,

I'm not sure if I understood the question correctly, but I think it was about embedding a PDF document from Google Drive. I don't speak Spanish, but English and Italian are OK. :)

Embedding a PDF file can be done like this.

* Go to your Google Drive account
* Right click the file you want to embed
* Select Share
* Change to "Anyone with the link can view"
* Copy the link
```
https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/view?usp=sharing
```
* Modify the last part of the link (view?usp=sharing => preview): 
```
https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/preview
```
* Embed the below code on a Joomla article
```
{google_docs}https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/preview{/google_docs}
```
* Repeat these steps for each file you want to embed.

Regards,
Petteri

**Comment by MARPENTA** [comment]
Gracias por la ayuda.
Funciona perfecto. Perdón por lo novato.

Gracias

2016-03-20 13:51 GMT-05:00 Petteri Kivimäki <notifications@github.com>:

> Hi,
>
> I'm not sure if I understood the question correctly, but I think it was
> about embedding a PDF document from Google Drive. I don't speak Spanish,
> but English and Italian are OK. :)
>
> Embedding a PDF file can be done like this.
>
>    - Go to your Google Drive account
>    - Right click the file you want to embed
>    - Select Share
>    - Change to "Anyone with the link can view"
>    - Copy the link
>
> https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/view?usp=sharing
>
>
>    - Modify the last part of the link (view?usp=sharing => preview):
>
> https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/preview
>
>
>    - Embed the below code on a Joomla article
>
> {google_docs}https://drive.google.com/file/d/0B8rrbLnAX55UaG4ybjBHVlVhZ28/preview{/google_docs}
>
>
>    - Repeat these steps for each file you want to embed.
>
> Regards,
> Petteri
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/petkivim/embed-google-docs/issues/2#issuecomment-198987837>
>



-- 
*Heisson Casallas Vega*

**Comment by petkivim** [comment]
You're welcome. Good to hear that the problem was solved. :)

Regards,
Petteri
