### ISSUE TITLE
"Uses Joomla! Update System" ??

### ISSUE THREAD

**Issue by BlackBrix** [petkivim/embed-google-docs#20]
Hello,
on the joomla extension page ( https://extensions.joomla.org/extensions/extension/social-web/social-display/google-docs-viewer/ )
it is statet:
"Uses Joomla! Update System" 
is this really true ?

I can not see any links in my joomla backend update sources (?)
(I use Joomla 3.8.x)

i think you need to provide an "update-stream" XML-File for this ...

**Comment by petkivim** [comment]
Hi,

Unfortunately, that information is incorrect. The plugin does not use Joomla! Update System.

Regards,
Petteri
