### ISSUE TITLE
responsive iframe -> suggestion

### ISSUE THREAD

**Issue by BlackBrix** [petkivim/embed-google-docs#21]
hello,
do you think it would be possible to integrate an option to this extension,
to make the iframes (pseudo-) responsive (with pure CSS)
including "automatic height adjust" of the iframe ?

I am not an CSS expert at all but
see this example here: --> https://24max.de/temp/responsive_iframe.htm
(press reload if it doesn't load the google content pdf into the iframe)
then make the browser window smaller and smaller an you see, 
that not only the width of the iframe is responsive but also the iframe-height 
(which is not the case with your extension now).

I am not sure if you need this different code for portait and landscape (?),

please note that I do not use the width and height within the <iframe>-tag, 
that is normally generated by this extension

**the markup:**
```  
<!DOCTYPE html>
<html>
<head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<title>responsive iframe test</title>
	<link rel="stylesheet" href="responsive_iframe_test.css" />
</head>
<body>
<h2>responsive iframe landscape</h2>
<div class="embed-container">
	<div class="embed-framewrapper-l">
		<iframe style="border: 0px none #000000" src="https://docs.google.com/viewer?url=https%3A%2F%2F24max.de%2Ftemp%2Ftest_landscape.pdf&amp;embedded=true&amp;hl=en"></iframe>
	</div>
</div>
<h2>responsive iframe portrait</h2>	
<div class="embed-container">
	<div class="embed-framewrapper-p">
		<iframe style="border: 0px none #000000" src="https://docs.google.com/viewer?url=https%3A%2F%2F24max.de%2Ftemp%2Ftest_portrait.pdf&amp;embedded=true&amp;hl=en"></iframe>
	</div>
</div>
</body>
</html>
```  
**the CSS:**

```  
.embed-container {
  margin: 0 auto;
  /* on desktop: */
  max-width: 125vh; /* limiting max-width and therefore indirectly the max-height of the embedded iframe, when browser window is of bigger width than the embedded content */
  /* on mobile devices, when holding the device horizontally: */
  /* max-width: 170vh; /* limiting max-width and therefore indirectly the max-height of the embedded iframe, when browser window is of bigger width than the embedded content */
  /* how to automate that ? */
}

/* orientation landscape ------------------------- */
.embed-framewrapper-l {
  position: relative; 
  padding-bottom: 81%; /* ratio 3x2 e.g. Document DIN-A4 landscape (66,6% + space for the google menu at the bottom) */
  height: 0; 
  overflow: hidden; 
  width: 100%;
  height: auto;
}

.embed-framewrapper-l iframe {
  position: absolute; 
  top: 0; 
  left: 0; 
  width: 100%; 
  height: 100%; 
}




/* orientation portrait -----------------------------*/
.embed-framewrapper-p {
  position: relative; 
  padding-bottom: 147%; /* ratio 2x3 e.g. Document DIN-A4 portrait */
  height: 0; 
  overflow: hidden;
  width: 100%;  
  height: auto;
}

.embed-framewrapper-p iframe {
  position: absolute; 
  top: 0; 
  left: 0; 
  width: 100%; 
  height: 100%; 
}
```

**Comment by petkivim** [comment]
Hi,

Thank you for your feedback. The easiest way to make the `iframe` scalable is to use `width` and `height` generated by the plugin and then use percent when defining width and height of a document. For example:

`
{google_docs}http://www.example.com/docs/document.pdf|width:80%|heigth:60%{/google_docs}
`

Best regards,
Petteri

**Comment by BlackBrix** [comment]
using percent does not work at all in my joomla template,
it's a very modern responsive template with bootstrap-framework and box bodel and all this new stuff ...

**Comment by BlackBrix** [comment]
in the meantime I realized this function (responsive iframe height) in my own fork of this repo

**Comment by petkivim** [comment]
That's great! Would you like to contribute your solution back to the master? I'd be happy to accept your pull request.
