### ISSUE TITLE
display in full screan

### ISSUE THREAD

**Issue by nassimalabed123** [petkivim/embed-google-docs#23]
HI ,the extention google docs viewer allows the display of documents in full screen,
If yes, how,help me please

**Comment by petkivim** [comment]
Hi,

The extension supports adding a link to the full screen version that opens in a new tab. This can be done setting `link:yes`. Link label can be customized using `link_label` parameter. 

`
{google_docs}document_url|link:yes|link_label:Label{/google_docs}
`.

**Comment by nassimalabed123** [comment]
HI
thank you very much
how  to customized using link_label parameter

**Comment by petkivim** [comment]
Hi,

Please see the example below. Just replace "Label" with your own custom label and it'll do the job.

`
{google_docs}document_url|link:yes|link_label:Label{/google_docs}
`

**Comment by nassimalabed123** [comment]
HI
I replaced label by full screen I had the same result: the display in the same window

**Comment by nassimalabed123** [comment]
HI
I replaced label by full screen I had the same result: the display in the same window like this:
{google_docs}circulaire.pdf|link:yes|link_label:full screen{/google_docs}

**Comment by petkivim** [comment]
Hi,

Can you post a link to the web site where you're trying to embed the document so I can have a look?

**Comment by nassimalabed123** [comment]
HI?
the sit is currently in maintenance I can sent you a screenshot
![google](https://user-images.githubusercontent.com/40548598/42127773-f6dd75b0-7c9e-11e8-891e-0c2f8a045542.png)

**Comment by nassimalabed123** [comment]
HI,
you have to click on full screen to have the display in full screen
what I want is a full screen display from the beginning

**Comment by petkivim** [comment]
Hi,

Thanks for the screenshot. The plugin seems to be working normally - it adds a link to the full screen document. You can adjust the size of the document on your page using `width` and `height` parameters. 

You can set absolute `width` and `height` using pixels:

```
{google_docs}document_url|width:200|height:200{/google_docs}
```

Or you can set relative `width` and `height` as well:

```
{google_docs}document_url|width:50%|height:50%{/google_docs}
```

**Comment by nassimalabed123** [comment]
HI,
Thank you very much for your answer

following the two syntaxes :
{google_docs}document_url|width:200|height:200{/google_docs}
{google_docs}document_url|width:200|height:200{/google_docs}
you have to click on the arrow to get this result :

![googles](https://user-images.githubusercontent.com/40548598/42133538-5eec7b78-7d2c-11e8-9bac-68588afe6c2e.png)



what I want:
have this result from the beginning

**Comment by nassimalabed123** [comment]
HI
the same result with this syntax:
{google_docs}document_url|width:50%|height:50%{/google_docs}
![google](https://user-images.githubusercontent.com/40548598/42133579-d78cba8e-7d2c-11e8-8ad3-d996dd3ab719.png)

**Comment by nassimalabed123** [comment]
HI
I tried both syntaxes:
{google_docs}document_url|width:200|height:200{/google_docs}
{google_docs}document_url|width:50%|height:50%{/google_docs}
the result is:
![google](https://user-images.githubusercontent.com/40548598/42136499-d112a436-7d5c-11e8-9bad-73d0c2df3d92.png)
you have to click on the arrow to get this result :

![googles](https://user-images.githubusercontent.com/40548598/42136505-eb3cbf04-7d5c-11e8-9c55-2357aaa1a761.png)
I want have the last display from the beginning  without clicking on the arrow

thank you very much

**Comment by petkivim** [comment]
If you want to access the full screen document by clicking a menu item then you should point the menu item to Google Docs Viewer directly. However, in full screen mode you cannot have the navigation bar / menu, some additional text or anything else in addition to the document itself. 

Unfortunately, without access to your website I cannot help you more than this with adjusting the size of the embedded document.

**Comment by nassimalabed123** [comment]
HI
I work with the version of joomla 3.9
the current version of php is 5.6.38
the free version of google docs viewer  is 1.4.2
I contacted my host to update the php version
this update poses problems for the extention google docs viewer 
the extention google docs viewer  supports the new version of php 7.2.9
can you help me please

**Comment by petkivim** [comment]
Hi,

Could you describe in more detail what kind of problems the update has caused? Have you checked the logs for error messages?

Regards,
Petteri

**Comment by nassimalabed123** [comment]
HI
I have not had a problem until now.
my question is :
if my host made the update of php version 5.6.38. to version 7.2.9
the extension google docs viewer supports this version of php
this update does not pose any problem knowing that
I work with the version of joomla 3.9
thank you very much

**Comment by petkivim** [comment]
Hi,

Embed Google Docs supports PHP 7 so there shouldn't be any problems. 

Regards,
Petteri

**Comment by nassimalabed123** [comment]
HI
thank you very much
