### ISSUE TITLE
Using the Edit Mode?

### ISSUE THREAD

**Issue by JamieClaye** [petkivim/embed-google-docs#26]
I setup a page with a PDF that has live check boxes and text fields but even in Edit mode they're not active.  Am I doing something wrong or is this feature not supported in this plug-in?

Thanks.

Here is a link to the page -https://dev.aeropac.org/index.php/join/10-aeropac-resources/67-aeropac-membership-form

**Comment by petkivim** [comment]
Hi,

Unfortunately, Google Docs Viewer does not support embedding fillable PDFs - the PDF is shown to the user, but the fields cannot be edited. Please see below a direct link to Google Docs Viewer:

https://docs.google.com/viewer?url=https://www.aeropac.org/AeroPAC_membership.pdf&embed=true

Unfortunately, this is a feature of Google Docs Viewer and therefore, the plugin cannot provide a workaround for it.

Best regards,
Petteri

**Comment by JamieClaye** [comment]
Thanks - hey, I've also noticed that sometimes the embedded  PDF file
doesn't show up right away and revisiting the page sometimes cures that.

And - how about an option to put the download link to the PDF at the top of
the page? That way if it fails to load at least they see something and it
can be downloaded.

Thanks again for the reply!

**Comment by petkivim** [comment]
> I've also noticed that sometimes the embedded PDF file doesn't show up right away and revisiting the page sometimes cures that

This seems to be a "feature" of Google Docs when embedding documents on an external site using `iframe`. Unfortunately, the plugin cannot do much about it.

At the moment the plugin supports adding a direct link to the document under the embedded document, but not above it. That's something that could be added in the future versions. 

Regards,
Petteri

**Comment by JamieClaye** [comment]
Thanks again for the quick response!  I look forward to a version were the
option for the link is at the top - at lease when the PDF fails to load the
user isn't looking at a blank screen (as the link is usually pushed way
down off the page)

Jamie
