### ISSUE TITLE
Thumbnail requires browser refresh to view

### ISSUE THREAD

**Issue by markdowd** [petkivim/embed-google-docs#27]
The following embed code is use in a JEvents event.
{google_docs}https://acappellasingers.co.uk/images/pdf/Spring_20_poster.pdf{/google_docs}

The thumbnail is only intermittently displayed (see https://acappellasingers.co.uk/index.php/upcoming/icalrepeat.detail/2020/03/29/1200/13/sacred-moments). Only when the page refreshes does it appear. is this a timing or a caching issue?

Great component, thanks.

**Comment by markdowd** [comment]
Just retried it and it only works after you've viewed the full-sized document.

**Comment by petkivim** [comment]
I accessed your site and embedded the document on my own test site, but unfortunately I wasn't able reproduce the issue. In both cases I was able to see the thumbnail immediately. Does the problem still occur? If not, it might have been a temporarily problem on Google Docs Viewer's side.

**Comment by markdowd** [comment]
Hmmm. Looks like it must have been a transient problem. Thnaks for looking into it anyway.
