### ISSUE TITLE
Can't see the files that weigh more than 1 mb

### ISSUE THREAD

**Issue by macagb** [petkivim/embed-google-docs#28]
On the site acesol.cl you cannot see the files that weigh more than 1 mb. You get the error: "There is no preview available." Sometimes it works.
Ex.: [](https://acesol.cl/noticias/item/1519-metodolog%C3%ADa-para-la-determinaci%C3%B3n-de-potencial-de-integraci%C3%B3n-de-tecnolog%C3%ADas-solares-t%C3%A9rmicas-para-aplicaciones-industriales-en-chile.html)

**Comment by macagb** [comment]
https://acesol.cl/noticias/item/1519-metodolog%C3%ADa-para-la-determinaci%C3%B3n-de-potencial-de-integraci%C3%B3n-de-tecnolog%C3%ADas-solares-t%C3%A9rmicas-para-aplicaciones-industriales-en-chile.html

**Comment by petkivim** [comment]
The maximum file size limit for the Google Doc Viewer preview should be 25MB so 1 MB is not be a problem.

I checked out your website, but unfortunately I was not able to reproduce the issue - I was able to see the preview without problems.

**Comment by macagb** [comment]
Thanks for your answer! I just used an other plugin for those files.

**Comment by petkivim** [comment]
You're welcome!
