### ISSUE TITLE
No preview available

### ISSUE THREAD

**Issue by bwganbrain** [petkivim/embed-google-docs#3]
I;m using the plugin but when I embed a google DRIVE document i get the error message of

NO preview available

What is causing this?

The domain is a google APPS for business domain, but I've also tried it a google apps account with the same results
I've followed the instructions correctly - I'm sure of that

Thanks

**Comment by petkivim** [comment]
Could you provide the URL of your site and the code that you use for embedding the document? Without more detailed information I'm not able to say anything further at the moment.

Br,
Petteri

**Comment by bwganbrain** [comment]
Thank you
I realised this morning that I'd not used the Text Editor when creating the
embed.
Until now I'd used the JCE editor and that adds other code, but having
tried the text editor I now know what works

thanks for your response

On 1 May 2016 at 09:00, Petteri Kivimäki <notifications@github.com> wrote:

> Could you provide the URL of your site and the code that you use for
> embedding the document? Without more detailed information I'm not able to
> say anything further at the moment.
>
> Br,
> Petteri
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/petkivim/embed-google-docs/issues/3#issuecomment-216024389>
>



-- 
Alan Davies

Tel: 0788 151 8442
Fax: 0871 253 0182

 www.davies.info
 thealandavies <https://www.linkedin.com/in/thealandavies>
  thealandavies
  @alandavies


This electronic message contains information from me which may be
privileged and confidential. The information is intended to be for the use
of the individual(s) or entity named above. If you are not the intended
recipient, be aware that any disclosure, copying, distribution or use of
the contents of this information is prohibited.
If you have received this electronic message in error, please notify us by
telephone or e-mail immediately.
Please do not print this e-mail unless you really need to.

**Comment by julisheot** [comment]
this is my website http://pa-brebes.go.id/layanan-publik/laporan/neraca-dan-arus-kas

**Comment by petkivim** [comment]
Hi,

There's an error in the URL that you're trying to embed. Currently you're using this URL:

```
https://drive.google.com/drive/folders/1JHjD2Hsrt4wybUuBEr8zPEYM-hS3OZhy<a href=&quot;https://drive.google.com/file/d/1caoXcB6Dyt88nyzgwXw4uuWot8wXYuQP/view&quot;>https://drive.google.com/file/d/1caoXcB6Dyt88nyzgwXw4uuWot8wXYuQP/view</a>/preview
```

Replace the incorrect URL with the URL below and the problem should be solved:

```
https://drive.google.com/file/d/1caoXcB6Dyt88nyzgwXw4uuWot8wXYuQP/preview
```

Regards,
Petteri
