### ISSUE TITLE
No pdf display

### ISSUE THREAD

**Issue by AndyMc52** [petkivim/embed-google-docs#30]
I have downloaded and enabled your plug-in. I am convinced that this is exactly what I need to display some genealogy documents that are produced (as PDF files) by my Family Tree Maker software. I have developed a Joomla test article with a link to the pdf file (which is uploaded to the _images/myfamily/pdf_ folder). 

The link that I created is 
_{google_docs}images/myfamily/pdf/Taylor_Story.pdf{/google_docs}_

When I try to view the article, however, all I get is the grey frame with no content. Clearly, I am doing something wrong, but I have exhausted all of the ideas that I had thought of. I even tried viewing an external PDF (as opposed to one within my Joomla site). This had the same effect.

I'm running Joomla! 3.9.25 on PHP 7.4.15

Can you offer any suggestions

**Comment by petkivim** [comment]
Any chance you could share a link to your test article with me? That would help me to debug the problem.

Also, could you try to embed this document on your site to see whether the plugin works correctly? I just tried it on my test site and this code should work. 

```
{google_docs}https://www.tutorialspoint.com/java/java_tutorial.pdf{/google_docs}
```

**Comment by AndyMc52** [comment]
Thank you for getting back to me. The Test Article is at: [https://www.mcmenemy.org/all/index.php/testing/59-test2021a](url)

It's content is only:

```
This is a sample of an embedded PDF: 

{google_docs}https://www.tutorialspoint.com/java/java_tutorial.pdf{/google_docs}
 images/myfamily/pdf/Taylor_Story.pdf
{google_docs}images/myfamily/pdf/Taylor_Story.pdf{/google_docs}
```


and the raw html is

```
<p>This is a sample of an embedded PDF: </p>
<pre><code>{google_docs}https://www.tutorialspoint.com/java/java_tutorial.pdf{/google_docs}</code></pre>
<pre><code>images/myfamily/pdf/Taylor_Story.pdf</code></pre>
<pre><code></code></pre>
<pre><code>{google_docs}images/myfamily/pdf/Taylor_Story.pdf{/google_docs}</code></pre>
```

As you can see I have tried your test code... but still I get nothing.

**Comment by petkivim** [comment]
Thank you for the information. Please switch the `HTTPS` setting in the plugin configuration from `No` to `Yes`. I believe that it should resolve the problem.

**Comment by petkivim** [comment]
You can also set the value in the code:

```
{google_docs}https://www.tutorialspoint.com/java/java_tutorial.pdf|https:yes{/google_docs}

{google_docs}images/myfamily/pdf/Taylor_Story.pdf|https:yes{/google_docs}
```

**Comment by AndyMc52** [comment]
Many thanks. You are clearly a genius. It now works perfectly.
Stay safe, and stay well.
