### ISSUE TITLE
Upgrading from joomla 3.x to joomla 4.x

### ISSUE THREAD

**Issue by rambro** [petkivim/embed-google-docs#31]
Hi all,

I am upgrading my website from joomla 3.x to joomla 4.x, I am looking at your "Embed Google Docs Viewer" extension and I was wondering if you are going to up the extension to joomla 4.x. Thank you

Rick Ambrosino

**Comment by petkivim** [comment]
Hi @rambro 

The Embed Google Docs Viewer extension already supports Joomla 4.x. I've updated the directory listing accordingly.

Best regards,
Petteri

**Comment by rambro** [comment]
Hi petkvim,

Are you sure Embed Google Docs Viewer works with the latest version of joomla 4.x. I tried it on my 4.x website and no joy (doesn't work). The link part of the plugin works. Do I have to do anything special with the code in joomla 4.x? Let me give you a couple of links:

https://testsitej4.cloudaccess.host/index.php/memorial-day-parade-ceremony/line-of-march-2022

https://testsitej4.cloudaccess.host/index.php/veteran-support-services/united-veterans-beacon-house-inc

P.S. love this extension, that is why in want to use it on my joomla 4.x website. Thank you.

Rick Ambrosino

**Comment by petkivim** [comment]
Hi @rambro 

I just tested the plugin with Joomla 4.1.5 and it worked as expected so it shouldn't be a compatibility issue. I looked at the examples you shared and I noticed that the files you're trying to embed have spaces (` `) in their names. I assume you've embedded them replacing spaces (` `) with plus (`+`) characters, like this:

```
{google_docs}https://testsitej4.cloudaccess.host/downloads/United+Veterans+Beacon+House.pdf{/google_docs}
```

Instead, you should leave the spaces in the file name when embedding them. In that way, I was able to embed the files successfully on my test site:

```
{google_docs}https://testsitej4.cloudaccess.host/downloads/United Veterans Beacon House.pdf{/google_docs}
```

I believe that changing plus (`+`) characters to spaces (` `) in the file names inside the `{google_docs}` tags should fix your problem.

Best regards,
Petteri

**Comment by rambro** [comment]
Hi petkvim,

Wow, do I have egg on my face. I looked at the plugin and I forgot to fill in "base URL". I made the changes and it works!!!
I have to remember to fill in the plugin. Thank you for getting back to me. Cheers.

Rick Ambrosino

**Comment by petkivim** [comment]
Hi @rambro 

That's great news, I'm glad to hear that the problem was resolved. 

Best regards,
Petteri
