### ISSUE TITLE
google docs viewere is not working in joomla 3.6.2 website.

### ISSUE THREAD

**Issue by rambro** [petkivim/embed-google-docs#5]
Dear Petteri Kivimäki,

I heavy use your embed google docs on my website. I am using version 1.4.2 of this extension. I use your extension to show pdf files in my joomla articles. However, with joomla 3.6.2 every pdf file that I am using with this extension is showing my index.php code when I go to a particular joomla article. My website is "merrickpost1282.org".

Here are few links where the problem is happening in my articles:

http://merrickpost1282.org/blogs/180-line-of-march-2016.html
http://merrickpost1282.org/blogs/188-free-narcan-class.html
http://merrickpost1282.org/blogs/191-veterans-benefit-seminar-thursday-june-23rd-8-30am.html
http://merrickpost1282.org/blogs/186-memorial-day-program-2016.html
http://merrickpost1282.org/blogs/181-tentative-memorial-day-ceremony-pamphlet-2016.html
http://merrickpost1282.org/blogs/78-merrickpost1282ad.html

Rick

**Comment by petkivim** [comment]
Hi Rick,

Thanks for contacting me. It's nice to hear that you're using my Embed Google Docs plugin on your website.

I checked your website and I noticed that the URLs you're using do not work even if you try to access them directly, e.g.

http://merrickpost1282.org/downloads/2016+Line+of+March+and+Staging+Locations_v3.pdf
http://merrickpost1282.org/downloads/Memorial+Day+2016+Parade+Staging+Layout_v2.pdf
http://merrickpost1282.org/downloads/memorial+day+ceremony+pamphlet+2016.pdf

Fixing the URLs should fix the problem with the plugin.

Petteri

**Comment by rambro** [comment]
Dear Petteri Kivimäki,

Thanks for getting back to me. I am kind of slow in comprehending what I should be doing here, therefore bear with me. Lets look at one article I have, it is called "Free Narcan Class".

http://merrickpost1282.org/blogs/188-free-narcan-class.html

If I access this pdf directly, it brings me to a page, where I see only code: 

https://docs.google.com/viewer?url=http%3A%2F%2Fmerrickpost1282.org%2F%2Fdownloads%2FNarcan+Class+Flyer.pdf

What is this page (that is the app that is opening this page), shouldn't an app like adobe reader be opening this pdf file, if the user has it installed on his or her computer?

However on this page, if I click on open original document, the pdf file actually opens up and everything is fine.

Can you elaborate more on what I am doing wrong here with this code? Here is the code in the article itself:

{google_docs}/downloads/Narcan Class Flyer.pdf|width:600|height:400|link:yes|link_label:Narcan Class Flyer|border:1{/google_docs}

I keep my .pdf files in a folder called downloads, on my web hosters site: /httpdocs/downloads. 

CloudAccess hosts my website (http://www.cloudaccess.net/).

Rick

**Comment by petkivim** [comment]
Hi,

In this page (http://merrickpost1282.org/blogs/188-free-narcan-class.html) the plugin works correctly. The document is shown using Google Docs Viewer application that's an application for reading and editing different types of documents, e.g. PDF, Word documents and Excel spreadsheets. Just like Adobe Reader is an application for viewing PDF files. The benefit of using Google Docs Viewer is that the user does not need to have Adobe Viewer or some other PDF viewer application installed on his/hers device. However, it's always possible to download the original document and open it with another application, e.g. Adobe Reader.

You should remove the first ```/```character, but otherwise the code below is correct and Narcan Class Flyer.pdf document is embedded on your site using Google Docs Viewer.

```
{google_docs}/downloads/Narcan Class Flyer.pdf|width:600|height:400|link:yes|link_label:Narcan Class Flyer|border:1{/google_docs}
```

Petteri

**Comment by rambro** [comment]
Dear Petteri Kivimäki,

Removing the first "/" worked. Thank you very much!!!

One quick question before I leave you alone. When you access the document directly from the joomla article, it brings up the google docs viewer. Since is only a google docs viewer, you have to go through another step, for example, "open original document" in order to download the document in question. It cannot be done directly from the google docs viewer (because it only views the document, correct?).

Thanks again

Rick

**Comment by petkivim** [comment]
Hi Rick,

When you open a document on full screen mode in Google Docs Viewer there's the Download Original icon on the top right corner. After clicking the icon the original document is opened in a new tab/window. If you want to provide a direct link to the original document you could add it manually on your site below the embedded document, e.g.

```
<a href="http://merrickpost1282.org/downloads/Narcan%20Class%20Flyer.pdf" target="new">Original document</a>
```

Petteri

**Comment by julisheot** [comment]
excuse me, I'm trying to paste Google docs viewere in joomla 3.5.1 website with files from google drive ... but it doesn't work priview
