### ISSUE TITLE
google docs viewer not reponding 

### ISSUE THREAD

**Issue by coloradodv** [petkivim/embed-google-docs#6]
Hi Pet

I am using this plugin on this site - herculesuniversity.com

If you go to this page http://www.herculesuniversity.com/index.php/home/orientation

The google viewer only works part of the time - I am not sure what changed, as it was working very well, and then now in the last few days, the viewer only calls up the PDF occasionally. Also the view link seems to only occasionally work as well. I can go to the pages and it work, then hit refresh and nothing. Click the view full link and it work, and then click again and nothing. 

Do you think something may have changed with Google? We really rely heavily on this ap for the materials in this site. 

It is Joomla 3.4.6 - but I have a Dev site that is 3.6.2 and it is repsonding the same. 

Thanks!

George

**Comment by petkivim** [comment]
Hi George,

Another user contacted me regarding the same problem just yesterday. I was able to repeat your problem with Firefox on my own test site. It seems that Google has changed something recently or they're having problems with their service. I hope it's just a temporary problem that will be fixed soon. 

Br,
Petteri

**Comment by coloradodv** [comment]
Its all working again. - Yeah!
