### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by olebro** [petkivim/embed-google-docs#8]
Hi,

I'm searching for a pdf viewer and have looked at your module and read some of the reviews. It seem that you have made a pretty fine viewer.

What made me curious is the lack of updates. It would be very sad, if my site chrashes because of compabillities issues when updating my Joomla site. The last update I can see are from 28 match 2015.  Is it because you do not develop on the module or is it because it cant be any better?

Br.

Ole

**Comment by petkivim** [comment]
Hi,

Thank you for your message. There hasn't been any updates recently because I haven't received any requests for new features and the plugin has been compatible with new versions of Joomla!. This does not mean that I have quit developing it - there just hasn't been anything to do lately. :)

Br,
Petteri

**Comment by olebro** [comment]
Hi Petteri,
Thanks for your response. I'm pleased to hear, that you still are active in developing on the Google Doc module. I'm intending to install the module and I will return to you if anything unexpected appears.

Br 
Ole

**Comment by olebro** [comment]
I have just downloaded your extension and was notified with this :+1: 

This extension inserts backlinks to the developer and may impact SEO.

Could you please explain what that means ? I guess that it concerns your ability to oush updates, but i'm not sure. Please clarify.

BR.

ole

**Comment by petkivim** [comment]
I don't know what causes the warning, because the plugin does not insert backlinks to me and it should not impact SEO. I'd say it's a false alert.

Br,
Petteri
